{% set name = "dockerfile-parse" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dockerfile-parse-{{ version }}.tar.gz
  sha256: 3184ccdc513221983e503ac00e1aa504a2aa8f84e5de673c46b0b6eee99ec7bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - dockerfile_parse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/containerbuildsystem/dockerfile-parse
  summary: Python library for Dockerfile manipulation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
